server:
  port: 90
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: false
    allow-bean-definition-overriding: true
  datasource:
      driver-class-name: ${household.datasource.driver-class-name}
      url: jdbc:mysql://${household.datasource.host}:${household.datasource.port}/${household.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${household.datasource.username}
      password: ${household.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.cybercaelum.household-management.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    # 添加认证持久化配置
    persist-authorization: true
    # 添加标签排序
    tags-sorter: alpha
    # 添加操作排序
    operations-sorter: method
  # info 配置移到 info 节点下
  info:
    title: "家政"
    version: "1.0"
    description: "家政接口文档"

household:
  jwt:
    # 密钥
    user-secret-key: ${household.jwt.user-secret-key}
    # 过期时间
    user-ttl: ${springdoc.household.jwt.user-ttl}
    #令牌名字
    user-token-name: ${springdoc.household.jwt.user-token-name}
  alioss:
    endpoint: ${household.alioss.endpoint}
    access-key-id: ${household.alioss.access-key-id}
    access-key-secret: ${household.alioss.access-key-secret}
    bucket-name: ${household.alioss.bucket-name}
