server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs  # OpenAPI JSON 路径
  swagger-ui:
    path: /swagger-ui.html  # UI 界面路径
    operations-sorter: method  # 按方法排序
    tags-sorter: alpha        # 按字母排序标签
  info:
    title: 项目 API 文档
    version: 1.0.0
    description: 项目接口文档说明
  household:
    jwt:
      # 密钥
      user-secret-key: cybercaelum
      # 过期时间
      user-ttl: 720000
      #令牌名字
      user-token-name: token
